trigger:
- feature*
- hotfix*

pool:
  vmImage: ubuntu-latest

variables:
- group: WhiteSource Keys

steps:

- script: |
    mkdir /opt/thunderscan && curl -LJO https://download.defensecode.com/latest/clients/tscli.tar.gz
    tar -C /opt/thunderscan -xzf ./tscli.tar.gz && rm tscli.tar.gz
    echo $(Build.Repository.Git.SubmoduleCheckout) Build.Repository.Git.SubmoduleCheckout
    echo $(Build.SourceBranchName) Build.SourceBranchName
    echo $(Build.SourceBranch) Build.SourceBranch
    echo $(Build.Repository.Uri) Build.Repository.Uri
    echo $(Build.SourceVersion) Build.SourceVersion

  displayName: Download ThunderScan CLI

- script: |
    /opt/thunderscan/tscli --git $(Build.Repository.Uri) --branch $(Build.SourceBranch) \
    --report --formats "html,json,sarif" --filename ThunderScan-Report
  env:
    THUNDERSCAN_SCAN_PARENT_ID: $(Build.Repository.Name)
    THUNDERSCAN_SCAN_NAME: $(Build.SourceBranchName)-$(Build.SourceVersion)
    THUNDERSCAN_AUTO_CREATE_PARENT: true
    THUNDERSCAN_API_TOKEN: $(THUNDERSCAN_API_TOKEN)
    THUNDERSCAN_API_URL: $(THUNDERSCAN_API_URL)
  displayName: Run ThunderScan SAST
  